package com.tiangouforum.domain;

import java.io.Serializable;

/**
 * @Author Du Yihong
 * Decription：用户信息
 * Date Create in 2018/1/28
 */
public class Frmuserinf implements Serializable {

    private static final long serialVersionUID = 1;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frmuserinf.userregnam
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    private String userregnam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frmuserinf.userpasswd
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    private String userpasswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frmuserinf.userregnam
     *
     * @return the value of frmuserinf.userregnam
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public String getUserregnam() {
        return userregnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frmuserinf.userregnam
     *
     * @param userregnam the value for frmuserinf.userregnam
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void setUserregnam(String userregnam) {
        this.userregnam = userregnam == null ? null : userregnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frmuserinf.userpasswd
     *
     * @return the value of frmuserinf.userpasswd
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public String getUserpasswd() {
        return userpasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frmuserinf.userpasswd
     *
     * @param userpasswd the value for frmuserinf.userpasswd
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void setUserpasswd(String userpasswd) {
        this.userpasswd = userpasswd == null ? null : userpasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Frmuserinf other = (Frmuserinf) that;
        return (this.getUserregnam() == null ? other.getUserregnam() == null : this.getUserregnam().equals(other.getUserregnam()))
            && (this.getUserpasswd() == null ? other.getUserpasswd() == null : this.getUserpasswd().equals(other.getUserpasswd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserregnam() == null) ? 0 : getUserregnam().hashCode());
        result = prime * result + ((getUserpasswd() == null) ? 0 : getUserpasswd().hashCode());
        return result;
    }
}