package com.tiangouforum.domain;

import java.util.ArrayList;
import java.util.List;
/**
 * @Author Du Yihong
 * Decription：用户信息Example
 * Date Create in 2018/1/28
 */
public class FrmuserinfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public FrmuserinfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserregnamIsNull() {
            addCriterion("userregnam is null");
            return (Criteria) this;
        }

        public Criteria andUserregnamIsNotNull() {
            addCriterion("userregnam is not null");
            return (Criteria) this;
        }

        public Criteria andUserregnamEqualTo(String value) {
            addCriterion("userregnam =", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamNotEqualTo(String value) {
            addCriterion("userregnam <>", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamGreaterThan(String value) {
            addCriterion("userregnam >", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamGreaterThanOrEqualTo(String value) {
            addCriterion("userregnam >=", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamLessThan(String value) {
            addCriterion("userregnam <", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamLessThanOrEqualTo(String value) {
            addCriterion("userregnam <=", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamLike(String value) {
            addCriterion("userregnam like", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamNotLike(String value) {
            addCriterion("userregnam not like", value, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamIn(List<String> values) {
            addCriterion("userregnam in", values, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamNotIn(List<String> values) {
            addCriterion("userregnam not in", values, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamBetween(String value1, String value2) {
            addCriterion("userregnam between", value1, value2, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserregnamNotBetween(String value1, String value2) {
            addCriterion("userregnam not between", value1, value2, "userregnam");
            return (Criteria) this;
        }

        public Criteria andUserpasswdIsNull() {
            addCriterion("userpasswd is null");
            return (Criteria) this;
        }

        public Criteria andUserpasswdIsNotNull() {
            addCriterion("userpasswd is not null");
            return (Criteria) this;
        }

        public Criteria andUserpasswdEqualTo(String value) {
            addCriterion("userpasswd =", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdNotEqualTo(String value) {
            addCriterion("userpasswd <>", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdGreaterThan(String value) {
            addCriterion("userpasswd >", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdGreaterThanOrEqualTo(String value) {
            addCriterion("userpasswd >=", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdLessThan(String value) {
            addCriterion("userpasswd <", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdLessThanOrEqualTo(String value) {
            addCriterion("userpasswd <=", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdLike(String value) {
            addCriterion("userpasswd like", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdNotLike(String value) {
            addCriterion("userpasswd not like", value, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdIn(List<String> values) {
            addCriterion("userpasswd in", values, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdNotIn(List<String> values) {
            addCriterion("userpasswd not in", values, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdBetween(String value1, String value2) {
            addCriterion("userpasswd between", value1, value2, "userpasswd");
            return (Criteria) this;
        }

        public Criteria andUserpasswdNotBetween(String value1, String value2) {
            addCriterion("userpasswd not between", value1, value2, "userpasswd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table frmuserinf
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 28 18:57:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table frmuserinf
     *
     * @mbg.generated Sun Jan 28 18:57:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}